# Development Dockerfile
FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN --no-cache npm install

# Run dev server by default
EXPOSE 5173

CMD ["npm", "run", "dev"]
